 'use client';
import {useEffect,useState} from 'react';
import {adminApi,type AdminExam} from '@/lib/api';
import type {User} from '@/lib/types';
import {message,statusFa} from '@/lib/format';
export function AdminExamStudents(){
 const [exams,setExams]=useState<AdminExam[]>([]),[students,setStudents]=useState<User[]>([]),[examId,setExamId]=useState(''),[assigned,setAssigned]=useState<User[]>([]),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 async function load(){setLoading(true);setError('');try{const [e,s]=await Promise.all([adminApi.exams(),adminApi.students()]);setExams(e);setStudents(s)}catch(e){setError(message(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{let active=true;setAssigned([]);setSelected([]);setSuccess('');if(!examId)return;setBusy(true);setError('');adminApi.participants(examId).then(s=>{if(active)setAssigned(s)}).catch(e=>{if(active)setError(message(e))}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[examId]);
 async function assign(){setBusy(true);setError('');setSuccess('');try{await adminApi.assign(examId,selected);setAssigned(await adminApi.participants(examId));setSelected([]);setSuccess('دانشجویان به آزمون تخصیص داده شدند. پس از انتشار استاد، آزمون در پنل آن‌ها نمایش داده می‌شود.')}catch(e){setError(message(e))}finally{setBusy(false)}}
 async function remove(studentId:string){if(!window.confirm('این دانشجو از آزمون حذف شود؟'))return;setBusy(true);setError('');setSuccess('');try{await adminApi.remove(examId,studentId);setAssigned(await adminApi.participants(examId))}catch(e){setError(message(e))}finally{setBusy(false)}}
 const exam=exams.find(e=>e.id===examId);const candidates=students.filter(s=>!assigned.some(a=>a.id===s.id)&&(s.fullName.includes(search)||s.universityId.includes(search)));
 return <section className="card space-y-5 p-7"><h2 className="text-xl font-bold">تخصیص دانشجویان به آزمون استاد</h2><p className="muted">استاد و درس هر آزمون مشخص است. دانشجویان را به همان آزمون متصل کنید.</p><button type="button" className="btn btn-outline" disabled={loading||busy} onClick={load}>تازه‌سازی آزمون‌ها و دانشجویان</button>{loading?<p role="status">در حال بارگذاری…</p>:<><label className="block space-y-2"><span>انتخاب آزمون</span><select className="field" disabled={busy} value={examId} onChange={e=>setExamId(e.target.value)}><option value="">انتخاب آزمون استاد</option>{exams.filter(e=>e.status!=='CANCELLED').map(e=><option key={e.id} value={e.id}>{e.titleFa} — {e.professor.fullName} ({e.professor.universityId}) — {e.course.titleFa} — {statusFa(e.status)}</option>)}</select></label>{!exams.length&&<p className="muted">ابتدا استاد باید پیش‌نویس آزمون را ایجاد کند.</p>}</>}{exam&&<><p className="text-sm muted">استاد: {exam.professor.fullName} • درس: {exam.course.titleFa} • وضعیت: {statusFa(exam.status)}</p><h3 className="font-bold">دانشجویان تخصیص‌یافته ({assigned.length})</h3>{assigned.length?assigned.map(s=><div className="row" key={s.id}><span>{s.fullName} — {s.universityId}</span><button className="btn btn-danger" disabled={busy} onClick={()=>remove(s.id)}>حذف از آزمون</button></div>):<p className="muted">هنوز دانشجویی تخصیص داده نشده است.</p>}<p className="text-sm muted">دانشجویی که آزمون را شروع کرده باشد قابل حذف نیست.</p><label className="block space-y-2"><span>جستجوی دانشجو با نام یا کد دانشجویی</span><input className="field" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="max-h-72 overflow-auto space-y-2">{candidates.map(s=><label key={s.id} className="flex items-center gap-3 rounded-lg border p-3"><input type="checkbox" disabled={busy} checked={selected.includes(s.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,s.id]:v.filter(id=>id!==s.id))}/><span>{s.fullName} — {s.universityId}</span></label>)}</div><button className="btn btn-primary" disabled={busy||!selected.length} onClick={assign}>{busy?'در حال ذخیره…':`تخصیص دانشجویان انتخاب‌شده (${selected.length})`}</button></>}{error&&<p role="alert" className="text-[var(--danger-ink)]">{error}</p>}{success&&<p role="status" className="text-[var(--accent)]">{success}</p>}</section>;
}
